# Generated by Django 3.2.13 on 2022-09-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0030_remove_ads_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='condition',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=100),
        ),
    ]
