# Generated by Django 3.2.13 on 2022-09-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0032_auto_20220926_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='regsiteration_url',
            new_name='no_of_slots',
        ),
    ]
