# Generated by Django 3.2.13 on 2022-10-07 13:42

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('ads', '0034_ads_img_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsimages',
            name='image',
        ),
        migrations.AddField(
            model_name='ads',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
